# Generated by Django 5.0.1 on 2024-03-04 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRatingComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.CharField(max_length=500)),
                ("comment", models.CharField(max_length=500)),
                ("review", models.CharField(max_length=500)),
                ("catalog", models.CharField(max_length=500)),
                ("comment_type", models.CharField(max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Rating Comment",
                "verbose_name_plural": "User Rating Comments",
                "db_table": "user_rating_comment",
            },
        ),
    ]
